[package]
name = "knot"
version = "0.1.0"
authors = ["William Brandon"]

[dependencies]
nalgebra = "0.13.1"
alga = "0.5.2"
approx = "0.1.1"
rand = "0.3.17"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
kiss3d = "0.11.0"
glfw = "0.15"
rayon = "0.8.2"
clap = "2.27.1"
