[package]
name = "interactive_symmetry_adjust"
version = "0.1.0"
authors = ["William Brandon"]

[dependencies]
knot = { path = "../../knot" }
knot_visualize = { path = "../../knot_visualize" }
nalgebra = "0.13.1"
alga = "0.5.2"
kiss3d = "0.11.0"
glfw = "0.15"
